### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [gburton/Responsive-osCommerce#1050]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by gburton** [comment]
Hello, thank you for contact.  This repo is defunct but I will tag in @ecartz for any action needed on the new repo: 
https://github.com/CE-PhoenixCart/

**Comment by ecartz** [comment]
I've looked at this twice.  The reason why I didn't do it was that there isn't really a best practices for reporting set up.  I mean, if GitHub offered private issues, that would be great.  As is, the best I really have is to go to https://phoenixcart.org/forum/ and register and send a PM.  I can put that into a SECURITY.md file.  Due to our release process, that probably wouldn't happen until 1.0.8.7 went live.

**Comment by ecartz** [comment]
[1.0.8.7](https://github.com/CE-PhoenixCart/PhoenixCart/releases/tag/v1.0.8.7) is now live, with a [SECURITY.md](https://github.com/CE-PhoenixCart/PhoenixCart/blob/master/.github/SECURITY.md) file.  As I've received no feedback on my previous post, I'm assuming that is satisfactory.  Closing.
