### ISSUE TITLE
Product Listing Module

### ISSUE THREAD

**Issue by gburton** [gburton/Responsive-osCommerce#302]
Needs a major revamp.

**Comment by gburton** [comment]
https://github.com/gburton/Responsive-osCommerce/issues/291
https://github.com/gburton/Responsive-osCommerce/issues/275
https://github.com/gburton/Responsive-osCommerce/issues/271
https://github.com/gburton/Responsive-osCommerce/issues/270
https://github.com/gburton/Responsive-osCommerce/issues/269
https://github.com/gburton/Responsive-osCommerce/issues/268
https://github.com/gburton/Responsive-osCommerce/issues/267

and possibly others

**Comment by BrockleyJohn** [comment]
The possibilities for this are practically endless, but I suspect many of them not to be particularly useful. Just because an option was there in 'classic' doesn't necessarily mean it's needed in bs...

Turning off prices and/or buy buttons is a topic that comes up every couple of months but I can't see the people who don't want to take money through their stores as a very large proportion of the user base.

Now that each piece of info displayed doesn't represent an extra column in the listing, it's perhaps not quite so important to be able to toggle them on and off.

What changes have bs shopowners made to the listing display - if any?

The only stuff I've done in this area was totally bespoke and unrelated to the listing display options - they were quite happy with what's shown for each listing.

**Comment by gburton** [comment]
And another:
https://github.com/gburton/Responsive-osCommerce/pull/337/

**Comment by gburton** [comment]
> Just because an option was there in 'classic' doesn't necessarily mean it's needed in bs...

Exactly.

**Comment by gburton** [comment]
https://github.com/gburton/Responsive-osCommerce/pull/353

**Comment by gburton** [comment]
All issues in product_listing module should now be solved. https://github.com/gburton/Responsive-osCommerce/pull/356
